# Use the official PostgreSQL image as the base
FROM postgres:18.2-alpine

# Set environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_DB postgres
ENV POSTGRES_PASSWORD postgres

# Expose the PostgreSQL port if needed (default is 5432)
EXPOSE 5432