FROM dpage/pgadmin4:9.12

ENV PGADMIN_DEFAULT_EMAIL="pgadmin4@pgadmin.org"
ENV PGADMIN_DEFAULT_PASSWORD="admin"
ENV PGADMIN_CONFIG_SERVER_MODE="False"
ENV PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED="False"

USER root
COPY /pgadmin/servers.json /pgadmin4/servers.json
COPY /pgadmin/pgpass /var/lib/pgadmin/pgpass

# Set the permissions
RUN chmod 600 /var/lib/pgadmin/pgpass
RUN chown pgadmin:root /var/lib/pgadmin/pgpass
RUN chown pgadmin:root /pgadmin4/servers.json


USER pgadmin